logging:
  level:
    org.springframework.web.client: TRACE
    org.springframework.http.client: TRACE
    org.springframework.security: DEBUG
security:
  user:
    name: jose
    password: mypass
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.100.5:5432/auth
    username: postgres
    password: sa
